# Server settings
server:
    tomcat:
        basedir: /var/tmp/oneblog/blog-admin
# SPRING PROFILES
spring:
    profiles:
        include: [center-dev]

# logging settings
logging:
    config: classpath:logback-spring.xml
    path: /var/tmp/oneblog/blog-admin

####################################自定义配置##########################################
app:
    # 是否启用kaptcha验证码
    enableKaptcha: ${ONEBLOG_APP_ENABLE_KAPTCHA:false}
    # 启用后，项目在启动时会打印数据库（Mysql和Redis）链接信息（包含密码）
    # 代码请参考
    enabledConfigLog: ${ONEBLOG_APP_ENABLE_CONFIGLOG:false}
    # shiro配置项
    shiro:
        loginUrl: "/passport/login/"
        successUrl: "/"
        unauthorizedUrl: "/error/403"
####################################自定义配置##########################################
